/// <reference path='definitions/jquery.d.ts' />
/// <reference path='definitions/jquery.repeatedclick.d.ts' />
/// <reference path='definitions/signalr.d.ts' />
/// <reference path='drawing/Brush.ts' />
/// <reference path='drawing/BrushControl.ts' />
/// <reference path='drawing/BrushCursor.ts' />
/// <reference path='drawing/HSL.ts'/>
/// <reference path="drawing/RGB.ts" />
/// <reference path='model/BrushAction.ts' />
/// <reference path='model/BrushState.ts' />
/// <reference path='model/BrushTracking.ts' />
/// <reference path='model/ChangeBrush.ts' />
/// <reference path='server/Api.ts' />
/// <reference path='server/ArtistApi.ts' />
/// <reference path='server/GuestApi.ts' />
/// <reference path='server/Notificator.ts' />
/// <reference path='MultiPaint.ts' />  
